### ISSUE TITLE
unable to download cellxgene's dataset?

### ISSUE THREAD

**Issue by jkobject** [laminlabs/lamindb#1304] opened 2023-11-16 14:58 UTC
Hi, I tried to follow everything and did this:
```
dataset = ln.Dataset.filter(name="cellxgene-census").one()
dataset.files.all()[0].save()
```
to get this error from django: `ProgrammingError: permission denied for table lnschema_core_file`

How would I go to download all the files in the dataset?

**Comment by jkobject** [comment] 2023-11-17 08:39
I understand now. So save() puts it in a database and here the database would be your version of cellxgene. So it is almost the opposite of stage(). I does help indeed. It might be me but it was not super clear as a concept from your page as I thought the database here is the local database I had. 

The thing I hadn't understood is that I had done `lamin init --storage ./data --schema bionty` but also did `lamin load laminlabs/cellxgene-census` it seems it now considers  cellxgene-census to be my database and not  ./data. I should have only done the former and then use the `using=` parameter to load from cellxgene?

Thanks!

**Comment by sunnyosun** [comment] 2023-11-17 09:16
Correct! Whenever you run init or load, that instance becomes your working instance. All the API DB operations are by default perform against your working instance unless you specify using.

Thanks your raising this confusion and we'll make sure to make this more clear in the guides!

**Comment by jkobject** [comment] 2023-11-17 09:35
I have been trying out things and following the transfer guide you shared, however it doesn't seem to really do what I want. 

I would want to end up with a new Dataset() object with all of the same files but in a way that they are physically stored on my local dataset. 
Even after `save() `and `stage()` I still see `file.path` pointing to s3://, 
Should I just do something like `file.path = file.stage()`? so that it no points to the posix path?

**Comment by Koncopd** [comment] 2023-11-17 09:39
Hi, @jkobject `file.path` always points to the source, which is on s3. To get the local path, you can use `file.stage()` (as you do), it won't download anything if it is cached already.

**Comment by falexwolf** [comment] 2023-11-17 09:47
Yeah, so, as Sergei (@Koncopd) says, the basic assumption is that if a piece of data is in the cloud, you have an auto-managed local cache for it.

Once you call `file.stage()` or `file.load()` once, you'll download the file, and it will remain in your local cache until you clean it.

You can access the local path through `file.stage()` and load the data into memory using `file.load()`.

The advantage of keeping the pointer to the original data on S3 is that you'll never confuse yourself - if you then transform any of the data and save new versions of it locally (or any of your storage location), you'll have data lineage that points to the original version of the file.

Still: We'd be happy to help you create an entirely local clone of the cellxgene-census instance if this is more sensible for you!

**Comment by falexwolf** [comment] 2023-11-17 09:49
The "tansfer data" guide really is meant as a way of transferring isolated data batches across instances in a canonical way.

**Comment by jkobject** [comment] 2023-11-17 10:04
I understand the idea. I have a few constraints however
- I really need to make sure that everything is on local so that I know if will load fast
- I won't have internet access on compute nodes so the data can only be on local
- I need to choose where the files are stored (the cache dir) so that I can use my compute cluster's predefined storage location for large datasets.

My initial idea was to create a new dataset -> add & download all the files from cellxgene (in this storage space)-> add some of my own files too -> do some preprocessing to each file one by one (not sure if there is a lamin way to do that)

**Comment by falexwolf** [comment] 2023-11-17 10:23
So, yeah, your 2 first constraints are already checkmarked, because once files are staged, you'll no longer need internet access. You can set the cache dir through `lamindb.setup.settings.storage.cache_dir` (or on the CLI).

But I see that it'll likely more sense to create an entire local clone of the instance. Everything would be simple if you started fresh and simply ingested local files or if we had the cloning feature ready. But we don't, so, a hack is needed to initialize your instance.

You can download files in whatever way you want, either through staging them to the auto-managed cache or through `file.path.download_to(local_filepath)` ([docs](https://lamin.ai/docs/lamindb.upath#lamindb.UPath.download_to)) if you want to control the precise file path (otherwise it will be based on the uid).

You can now loop over these local paths and update your File registry to point to the correct local version via:

```
orig_files = ln.File.filter().all()
for file, rel_path in zip(orig_files, rel_paths):
    file.storage = local_storage_root  # this is the storage record corresponding to your root directory
    file.key = rel_path_within_root  # this is a string
    file.key_is_virtual = False  # this indicates that you're using manually configured storage paths
    file.save()
```

Because the `key` already has a sensible relative path for Census and `key_is_virtual` is already `False`, you'll likely not need lines 2 & 3 in the loop, but simply point each file record to your root directory (the first line within the loop).

**Comment by jkobject** [comment] 2023-11-17 13:57
Thanks! I think I have everything I need for now on this topic :) I wills start working on this

**Comment by jkobject** [comment] 2023-11-17 14:08
Actually I just tried that and it doesn't seem to work. I get a `ValueError: save() prohibited to prevent data loss due to unsaved related object 'storage'.` and my local is defined as` local_storage_root=ln.Storage(root=ln.settings.storage)`

**Comment by falexwolf** [comment] 2023-11-17 15:17
(Sorry - was at a family event during the day.)

Any record needs to be saved before it can be associated to another record.

Hence, `local_storage_root.save()` needs to be called and you'll be good!

**Comment by jkobject** [comment] 2023-11-19 16:12
Sorry to continue bothering with this but I did try it and now am getting the issue:
 
`ValueError: Cannot assign "Storage(uid='HIuhQCHA', root=/home/ml4ig1/Documents code/data2, type='', updated_at=2023-11-19 14:49:24 UTC, created_by_id=1)": the current database router prevents this relation.`

**Comment by falexwolf** [comment] 2023-11-19 16:19
Sorry for what appears to be a bug and at least unexpected behavior! Let me try this.

**Comment by falexwolf** [comment] 2023-11-19 16:36
OK, here is a gist where I did what I described the above trying to reproduce your problem: https://gist.github.com/falexwolf/fc650846e950321a3423834d9727060e

Everything worked as expected.

Could you take a look or provide more info on how you went about things?

**Comment by jkobject** [comment] 2023-11-20 14:45
So your notebook worked on my end too: I updated my code so it does something like this:
```
files=[]
for file in cx_dataset.files.all()[:5]:
    try:
        file.save()
    except IntegrityError:
        print(f"File {file.uid} already exists in storage")
    # if location already has a file, don't save again
    file.path.download_to(f"./mytest/{file.key}")
    file.storage = default_storage
    try:
        file.save()
    except IntegrityError:
        print(f"File {file.uid} already exists in storage")
    files.append(file)
```
Then I thought I would create my own dataset like so:

```
dataset = ln.Dataset(
    files, name="test_cxgene", description="first 10 cxgene files"
)
dataset.save()
```

But get the error:
```
ValueError: Cannot add "File(uid='CAQPyYbcP4UjgiIfniQK', key='cell-census/2023-07-25/h5ads/d5c67a4e-a8d9-456d-a273-fa01adb1b308.h5ad', suffix='.h5ad', accessor='AnnData', description='Retina|d5c67a4e-a8d9-456d-a273-fa01adb1b308', size=190765719, hash='d8ZhFETfIiYt51mH7_7CtQ-23', hash_type='md5-n', visibility=0, key_is_virtual=False, updated_at=2023-11-20 14:23:20 UTC, storage_id=1, created_by_id=1)": the value for field "file" is None
```

It seems to be the last stage of creating a dataset from these new local files:

**Comment by falexwolf** [comment] 2023-11-20 14:54
Yes, this should work and it's tested.

Let me try to reproduce your problem.

**Comment by falexwolf** [comment] 2023-11-20 15:17
I see, because you ecepted the `IntegrityError`, some of your files aren't saved.

You should never have to write a try-except statement like this. There seems to be a bug in transferring metadata into your instance - @sunnyosun is going to look into it.

**Comment by falexwolf** [comment] 2023-11-20 17:51
There was a bug here - repeated data transfers weren't entirely idempotent. Now they are: https://github.com/laminlabs/lamindb/pull/1311

I didn't see it immediately because you had introduced the try-except statements.

We'll make a new lamindb release with the data loader and this bug fix and everything should work as expected.

**Comment by falexwolf** [comment] 2023-11-20 22:55
The bug fix is live in lamindb 0.62:
<img width="652" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/43d7a824-b9bc-49ad-8049-c149a6065aca">

**Comment by jkobject** [comment] 2023-11-21 09:08
wow amazing and you were able to also add the .df()

**Comment by jkobject** [comment] 2023-11-22 10:04
maybe one more remark, if I want to download all of it I get this error as I can't really set an organism since cellxgene contains multiple organisms

AssertionError: Gene requires to specify a organism name via `organism=` or `lb.settings.organism=`!

what is the solution to have a storage with multiple organisms?

**Comment by falexwolf** [comment] 2023-11-22 11:37
An alternative way of doing it is to stratify your download script into two parts, first register all human data, and then register all mouse data and changing the global setting in between.

**Comment by jkobject** [comment] 2023-11-22 13:12
I understand, except this error occurs in the `file.save()` function which doesn't seem to accept an `organism=` parameter..

**Comment by sunnyosun** [comment] 2023-11-22 13:43
You need to to provide the `organism=` to `File`, not to `.save()`.

**Comment by sunnyosun** [comment] 2023-11-24 10:26
> You need to to provide the `organism=` to `File`, not to `.save()`. Tried to explain here: https://lamin.ai/docs/bio-registries#manage-registries-across-organism, but I see that as the error only show up upon save, this can be not very clear. We'll improve the error propagation here, thanks for raising it!

To correct my answer above, if you save files with the transfer, you can only use global settings for the organism since you don't call the File constructor.

To set the organism for each file (which is already annotated), you can:
```
for file in cx_dataset.files.all():
    organism_record = file.organism.first()
    lb.settings.organism = organism_record
    ...
    file.save()
```

**Comment by jkobject** [comment] 2023-11-27 14:35
> To correct my answer above, if you save files with the transfer, you can only use global settings for the organism since you don't call the File constructor.

So this is what I had tried at some point but the issue is that many files in cx_dataset had no organisms set

**Comment by sunnyosun** [comment] 2023-11-27 15:06
> > To correct my answer above, if you save files with the transfer, you can only use global settings for the organism since you don't call the File constructor.
> 
> So this is what I had tried at some point but the issue is that many files in `cx_dataset` had no organisms set
> 
> here `cx_dataset = ln.Dataset.using("laminlabs/cellxgene-census").one()`

You are right, we also noticed that some files don't have metadata when we queried via the census production API. But we will now have those files labeled directly using the cellxgene REST API so that everything should be labeled. This is going to be completed either later today or tomorrow. I'll ping you once we update the instance!

**Comment by sunnyosun** [comment] 2023-12-06 11:00
The new `laminlabs/cellxgene` instance is up and all files should be annotated appropriately now.

**Closed** 2024-10-15 15:13 UTC
