### ISSUE TITLE
`add_new_from_var_index` leads to unique key value error because it attempts to save values with no source again

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#2293] opened 2024-12-18 09:21 UTC
### Add a description

```python
sdata = sd.read_zarr("10zvc__10X__Visium__Mouse__brain__20220329__v1.3.0_attrs_attrs.zarr")

curator = ln.Curator.from_anndata(sdata.tables["table"],
                        var_index=bt.Gene.ensembl_gene_id,
                        categoricals={},
                        organism="mouse")
curator.validate()
curator.add_new_from_var_index()
```

leads to

```
---------------------------------------------------------------------------
UniqueViolation                           Traceback (most recent call last)
File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/backends/utils.py:105, in CursorWrapper._execute(self, sql, params, *ignored_wrapper_args)
    104 else:
--> 105     return self.cursor.execute(sql, params)

UniqueViolation: duplicate key value violates unique constraint "lnschema_bionty_gene_uid_key"
DETAIL:  Key (uid)=(6KCoBil6asUg) already exists.


The above exception was the direct cause of the following exception:

IntegrityError                            Traceback (most recent call last)
Cell In[16], line 1
----> 1 curator.add_new_from_var_index()

File ~/PycharmProjects/lamindb/lamindb/_curate.py:653, in AnnDataCurator.add_new_from_var_index(self, organism, **kwargs)
    646 """Update variable records.
    647 
    648 Args:
    649     organism: The organism name.
    650     **kwargs: Additional keyword arguments to pass to create new records.
    651 """
    652 self._kwargs.update({"organism": organism} if organism else {})
--> 653 self._save_from_var_index(validated_only=False, **self._kwargs, **kwargs)

File ~/PycharmProjects/lamindb/lamindb/_curate.py:628, in AnnDataCurator._save_from_var_index(self, validated_only, organism)
    624 def _save_from_var_index(
    625     self, validated_only: bool = True, organism: str | None = None
    626 ):
    627     """Save variable records."""
--> 628     update_registry(
    629         values=list(self._adata.var.index),
    630         field=self.var_index,
    631         key="var_index",
    632         using_key=self._using_key,
    633         validated_only=validated_only,
    634         organism=organism,
    635         source=self._sources.get("var_index"),
    636         exclude=self._exclude.get("var_index"),
    637     )

File ~/PycharmProjects/lamindb/lamindb/_curate.py:2307, in update_registry(values, field, key, using_key, validated_only, df, organism, dtype, source, exclude, **kwargs)
   2299                 init_kwargs["dtype"] = "cat" if dtype is None else dtype
   2300             non_validated_records.append(
   2301                 registry(
   2302                     **init_kwargs,
   (...)
   2305                 )
   2306             )
-> 2307     ln_save(non_validated_records)
   2309 # save parent labels for ulabels, for example a parent label "project" for label "project001"
   2310 if registry == ULabel and field.field.name == "name":

File ~/PycharmProjects/lamindb/lamindb/_save.py:83, in save(records, ignore_conflicts)
     79 if non_artifacts:
     80     non_artifacts_old, non_artifacts_new = partition(
     81         lambda r: r._state.adding or r.pk is None, non_artifacts
     82     )
---> 83     bulk_create(non_artifacts_new, ignore_conflicts=ignore_conflicts)
     84     if non_artifacts_old:
     85         bulk_update(non_artifacts_old)

File ~/PycharmProjects/lamindb/lamindb/_save.py:114, in bulk_create(records, ignore_conflicts)
    112     records_by_orm[record.__class__].append(record)
    113 for registry, records in records_by_orm.items():
--> 114     registry.objects.bulk_create(records, ignore_conflicts=ignore_conflicts)

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/models/manager.py:87, in BaseManager._get_queryset_methods.<locals>.create_method.<locals>.manager_method(self, *args, **kwargs)
     85 @wraps(method)
     86 def manager_method(self, *args, **kwargs):
---> 87     return getattr(self.get_queryset(), name)(*args, **kwargs)

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/models/query.py:835, in QuerySet.bulk_create(self, objs, batch_size, ignore_conflicts, update_conflicts, update_fields, unique_fields)
    833 if objs_without_pk:
    834     fields = [f for f in fields if not isinstance(f, AutoField)]
--> 835     returned_columns = self._batched_insert(
    836         objs_without_pk,
    837         fields,
    838         batch_size,
    839         on_conflict=on_conflict,
    840         update_fields=update_fields,
    841         unique_fields=unique_fields,
    842     )
    843     connection = connections[self.db]
    844     if (
    845         connection.features.can_return_rows_from_bulk_insert
    846         and on_conflict is None
    847     ):

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/models/query.py:1875, in QuerySet._batched_insert(self, objs, fields, batch_size, on_conflict, update_fields, unique_fields)
   1870 for item in [objs[i : i + batch_size] for i in range(0, len(objs), batch_size)]:
   1871     if bulk_return and (
   1872         on_conflict is None or on_conflict == OnConflict.UPDATE
   1873     ):
   1874         inserted_rows.extend(
-> 1875             self._insert(
   1876                 item,
   1877                 fields=fields,
   1878                 using=self.db,
   1879                 on_conflict=on_conflict,
   1880                 update_fields=update_fields,
   1881                 unique_fields=unique_fields,
   1882                 returning_fields=self.model._meta.db_returning_fields,
   1883             )
   1884         )
   1885     else:
   1886         self._insert(
   1887             item,
   1888             fields=fields,
   (...)
   1892             unique_fields=unique_fields,
   1893         )

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/models/query.py:1847, in QuerySet._insert(self, objs, fields, returning_fields, raw, using, on_conflict, update_fields, unique_fields)
   1840 query = sql.InsertQuery(
   1841     self.model,
   1842     on_conflict=on_conflict,
   1843     update_fields=update_fields,
   1844     unique_fields=unique_fields,
   1845 )
   1846 query.insert_values(fields, objs, raw=raw)
-> 1847 return query.get_compiler(using=using).execute_sql(returning_fields)

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/models/sql/compiler.py:1836, in SQLInsertCompiler.execute_sql(self, returning_fields)
   1834 with self.connection.cursor() as cursor:
   1835     for sql, params in self.as_sql():
-> 1836         cursor.execute(sql, params)
   1837     if not self.returning_fields:
   1838         return []

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/backends/utils.py:79, in CursorWrapper.execute(self, sql, params)
     78 def execute(self, sql, params=None):
---> 79     return self._execute_with_wrappers(
     80         sql, params, many=False, executor=self._execute
     81     )

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/backends/utils.py:92, in CursorWrapper._execute_with_wrappers(self, sql, params, many, executor)
     90 for wrapper in reversed(self.db.execute_wrappers):
     91     executor = functools.partial(wrapper, executor)
---> 92 return executor(sql, params, many, context)

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/backends/utils.py:100, in CursorWrapper._execute(self, sql, params, *ignored_wrapper_args)
     98     warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
     99 self.db.validate_no_broken_transaction()
--> 100 with self.db.wrap_database_errors:
    101     if params is None:
    102         # params default might be backend specific.
    103         return self.cursor.execute(sql)

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/utils.py:91, in DatabaseErrorWrapper.__exit__(self, exc_type, exc_value, traceback)
     89 if dj_exc_type not in (DataError, IntegrityError):
     90     self.wrapper.errors_occurred = True
---> 91 raise dj_exc_value.with_traceback(traceback) from exc_value

File ~/miniconda3/envs/lamindb/lib/python3.11/site-packages/django/db/backends/utils.py:105, in CursorWrapper._execute(self, sql, params, *ignored_wrapper_args)
    103     return self.cursor.execute(sql)
    104 else:
--> 105     return self.cursor.execute(sql, params)

IntegrityError: duplicate key value violates unique constraint "lnschema_bionty_gene_uid_key"
DETAIL:  Key (uid)=(6KCoBil6asUg) already exists.
```

I am working on the minimal working example. Pretty sure the issue is that values with no source get recreated in the `_curate` code

**Comment by Zethson** [comment] 2024-12-18 13:14
Debugging notes:

1. I cannot create a minimal reproducible example. Saving a gene without a source and having that gene in the `AnnData` object index and finally running `add_new_from_var_index` does not trigger the error.
2. `ENSMUSG00000035310` is one of the example genes.
________Debugger__________

3. When filtering for 
```python
existing_and_public_records = registry.from_values(
            list(values), field=field, **filter_kwargs_current
        )
```
the gene is NOT among those
4. It does however appear here:
```python
non_validated_labels = [
            i for i in values if i not in existing_and_public_labels
        ]
``` and is among those.

**Comment by sunnyosun** [comment] 2024-12-19 10:48
How can I debug this without a minimal example?

**Comment by Zethson** [comment] 2024-12-19 10:49
It's here https://github.com/laminlabs/lamindb/issues/2255#issuecomment-2553378215

**Comment by sunnyosun** [comment] 2024-12-19 10:51
Can we close this issue then if the problem is in from_values rather than curator?

**Closed** 2024-12-19 10:52 UTC
Labels: :bug: bug
